### PR TITLE
build(scripts): add class adoption script

### PR DESCRIPTION
**Pull request by akdetrick**
Adds command `npm run stats:classes <target>` to find all usage of NDS helper classes in a given local dir.

Screen Shot 2022-01-10 at 4 28 12 PM

#### How it works
1. the script reads `src/helper-classes` and compiles sass files into CSS
2. the CSS is parsed to get all the class names
3. every valid file in the target directory is searched for all the class names and results are tallied

### CODE REVIEW

**Comment by wrbrand** [comment]
My output seems to be different from yours:

```
will@Wills-MacBook-Air design_system % npm run stats:classes ~/Narmi/banking/             

> @narmi/design_system@1.26.0 stats:classes
> node ./scripts/class-adoption.mjs "/Users/will/Narmi/banking/"

Warning: You probably don't mean to use the color value white in interpolation here.
It may end up represented as white, which will likely produce invalid CSS.
Always quote color names when using them as strings or map keys (for example, "white").
If you really want to use the color value here, use '"" + $bgColor'.

  ╷
6 │   .bgColor--#{$bgColor} {
  │               ^^^^^^^^
  ╵
    - 6:15  root stylesheet

Warning: You probably don't mean to use the color value white in interpolation here.
It may end up represented as white, which will likely produce invalid CSS.
Always quote color names when using them as strings or map keys (for example, "white").
If you really want to use the color value here, use '"" + $color'.

   ╷
59 │   .fontColor--#{$color} {
   │                 ^^^^^^
   ╵
    - 59:17  root stylesheet


Helper class usage in /Users/will/Narmi/banking/:
┌───┬──────────────┐
│ # │ Class Name   │
├───┼──────────────┤
│ 4 │ margin--left │
└───┴──────────────┘
TOTAL CLASSES USED: 4

```

Does that actually accomplish what we want, here? I'm figuring we use more classes than that.

**Comment by akdetrick** [comment]
This is... not what I was expecting. Is your local checkout of `banking` on latest master?

**Comment by wrbrand** [comment]
Hm, my output does differ now that I try again with latest `master`:

```
will@Wills-MacBook-Air design_system % npm run stats:classes ~/Narmi/banking/   

> @narmi/design_system@1.26.0 stats:classes
> node ./scripts/class-adoption.mjs "/Users/will/Narmi/banking/"

Warning: You probably don't mean to use the color value white in interpolation here.
It may end up represented as white, which will likely produce invalid CSS.
Always quote color names when using them as strings or map keys (for example, "white").
If you really want to use the color value here, use '"" + $bgColor'.

  ╷
6 │   .bgColor--#{$bgColor} {
  │               ^^^^^^^^
  ╵
    - 6:15  root stylesheet

Warning: You probably don't mean to use the color value white in interpolation here.
It may end up represented as white, which will likely produce invalid CSS.
Always quote color names when using them as strings or map keys (for example, "white").
If you really want to use the color value here, use '"" + $color'.

   ╷
59 │   .fontColor--#{$color} {
   │                 ^^^^^^
   ╵
    - 59:17  root stylesheet


Helper class usage in /Users/will/Narmi/banking/:
┌───┬──────────────────────┐
│ # │ Class Name           │
├───┼──────────────────────┤
│ 2 │ fontWeight--semibold │
│ 1 │ padding--top--s      │
│ 1 │ margin--top--xs      │
│ 4 │ margin--all--l       │
│ 2 │ margin--right--l     │
│ 1 │ margin--bottom--xl   │
│ 4 │ margin--left         │
└───┴──────────────────────┘
TOTAL CLASSES USED: 15
```

This still doesn't seem exhaustive, for instance it's missing the `margin--top--l` usage in https://github.com/narmi/banking/blob/724d636acec91a7b17a30a26129b00de63c8dc09/azul/components/transfer/SimpleTransferForm.jsx#L230

**Review by wrbrand — APPROVED** [review]
This now gives me 39 results on latest master, which seems correct, and I can't find any obvious omissions or duplications.

**Pull request merged**
